#!/usr/bin/env bash
# Generate LVGL C font files used by firmware.
#
# Run from the project root:
#   firmware/tools/gen_zfull_fonts.sh
#
# Requirements:
#   - lv_font_conv in PATH
#   - python3 in PATH
#   - Zfull-GB.ttf at backend/assets/fonts/vector/Zfull-GB.ttf
#
# To use another font, pass a repo-relative path:
#   ZFULL_TTF=backend/assets/fonts/vector/Zfull-GB.ttf firmware/tools/gen_zfull_fonts.sh
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

readonly OUT_DIR="firmware/main/resources/fonts"
readonly DEFAULT_ZFULL_TTF="backend/assets/fonts/vector/Zfull-GB.ttf"
ZFULL_TTF="${ZFULL_TTF:-$DEFAULT_ZFULL_TTF}"

die() {
    echo "error: $*" >&2
    exit 1
}

need() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

require_repo_relative() {
    local name="$1" value="$2"
    [ -n "$value" ] || die "$name must not be empty"
    case "$value" in
        /* | ../* | */../*)
            die "$name must be a repo-relative path: $value"
            ;;
    esac
}

need lv_font_conv
need python3
require_repo_relative ZFULL_TTF "$ZFULL_TTF"

cd "$REPO_ROOT"

if [ ! -f "$ZFULL_TTF" ]; then
    echo "error: missing Zfull font: $ZFULL_TTF" >&2
    echo "copy Zfull-GB.ttf to backend/assets/fonts/vector/ or set ZFULL_TTF to a repo-relative path" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"

postprocess_font() {
    local file="$1" glyphs="$2"

    FONT_PATH="$ZFULL_TTF" GLYPHS="$glyphs" python3 - "$file" <<'PY'
import os
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")

text = text.replace(
    '#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n#include "lvgl.h"\n#else\n#include "lvgl/lvgl.h"\n#endif',
    '#include "lvgl.h"',
)

lines = []
for line in text.splitlines():
    if line.startswith(" * Opts: "):
        lines.extend(
            [
                " * Generated by: firmware/tools/gen_zfull_fonts.sh",
                f" * Font: {os.environ['FONT_PATH']}",
                f" * Glyphs: {os.environ['GLYPHS']}",
            ]
        )
    else:
        lines.append(line)

path.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8")
PY
}

generate_zfull_16_symbols() {
    # Keep high-plane emoji out of the LVGL text font. LVGL fmt_txt cmap stores
    # range_length as uint16_t, so BMP symbols are reliable while U+1Fxxx
    # symbols should use a dedicated image/font path instead.
    python3 - <<'PY'
import sys

BASE_SYMBOLS = (
    r""" !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~"""
    "，。！？：；、（）《》【】“”‘’—…·"
    "☀☁☂☃⚡❄"
    "¥€£₿¢"
    "←↑→↓↖↗↘↙↔↕➜➝➞➤"
    "℃℉°‰"
    "±×÷≈≠≤≥∞√"
    "～–「」『』〈〉〔〕〖〗"
    "©®™§¶"
)

hanzi = []
for lead in range(0xB0, 0xF8):
    for trail in range(0xA1, 0xFF):
        try:
            hanzi.append(bytes((lead, trail)).decode("gb2312"))
        except UnicodeDecodeError:
            pass

if len(hanzi) != 6763:
    raise SystemExit(f"expected 6763 GB2312 Hanzi, got {len(hanzi)}")

sys.stdout.write(BASE_SYMBOLS + "".join(hanzi))
PY
}

generate_font() {
    local output="$1" size="$2" name="$3" glyphs="$4"
    shift 4

    echo "generating $OUT_DIR/$output"
    lv_font_conv \
        --no-compress \
        --bpp 1 \
        --size "$size" \
        --font "$ZFULL_TTF" \
        --autohint-off \
        "$@" \
        --format lvgl \
        --output "$OUT_DIR/$output" \
        --lv-font-name "$name"
    postprocess_font "$OUT_DIR/$output" "$glyphs"
}

ZFULL_16_SYMBOLS="$(generate_zfull_16_symbols)"

generate_font zfull_16.c 16 Zfull_16 "GB2312 + ASCII + selected BMP symbols" --symbols "$ZFULL_16_SYMBOLS"
generate_font zfull_12.c 12 Zfull_12 "ASCII 0x20-0x7F" -r 0x20-0x7F

echo "done"
